### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by SHoltom** [textbook/atom-tracker#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-tracker](https://github.com/textbook/atom-tracker) package, v0.3.1
### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Users/shahziaholtom/.atom/packages/atom-tracker/lib/services/file-utils.coffee:9

TypeError: Cannot read property 'match' of undefined
    at Object.module.exports.eraseComment (/Users/shahziaholtom/.atom/packages/atom-tracker/lib/services/file-utils.coffee:9:33)
    at /Users/shahziaholtom/.atom/packages/atom-tracker/lib/services/tracker-utils.coffee:81:19
    at IncomingMessage.<anonymous> (/Users/shahziaholtom/.atom/packages/atom-tracker/lib/services/tracker-utils.coffee:114:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```
### Commands

```
     -0:51.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:51 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:51 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:47.4.0 atom-tracker:finish-story (atom-workspace.workspace.scrollbars-visible-always.theme-octocat-syntax.theme-one-light-ui)
     -0:32.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:32.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:21.6.0 atom-tracker:create-config (atom-text-editor.editor.is-focused)
     -0:20.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:19.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:19.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.7.0 atom-tracker:finish-story (atom-workspace.workspace.scrollbars-visible-always.theme-octocat-syntax.theme-one-light-ui)
  2x -0:12.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:12.1.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "octocat-syntax"
    ]
  },
  "atom-tracker": {
    "trackerToken": "c21fab31ab94ce127005b39c33b6cf9c"
  }
}
```
### Installed Packages

``` coffee
# User
atom-tracker, v0.3.1
color-picker, v2.1.1
octocat-syntax, v0.1.5
pigments, v0.26.0

# Dev
No dev packages
```

**Comment by textbook** [comment]
Story apparently had no description when the code hit https://github.com/textbook/atom-tracker/blob/master/lib/services/file-utils.coffee#L9
